torchrun --master_port 2995 --nnodes=1 --nproc_per_node=8 train.py \
--model VeSpa-H/2 \
--dataset-type imagenet \
--image-only True \
--data-path /maindata/data/shared/multimodal/zhengcong.fei/code/vespa/data/imagenet_tag.json \
--anna-path /maindata/data/shared/multimodal/zhengcong.fei/code/vespa/data/imagenet_tag.json \
--image-size 256 \
--text_encoder_type t5 \
--global-batch-size 64 \
--epochs 20 \
--warmup_epochs 0 \
--accum_iter 8 \
--eval_steps 10000000 \
--lr 1e-4 \
--latent_space True \
--global-seed 520 \
--resume /maindata/data/shared/multimodal/zhengcong.fei/code/vespa/results/VeSpa-H-2-imagenet-image-True/checkpoints/ckpt2.pt